server:
  port: 7634

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
